name       : libunistring
version    : 0.9.10
release    : 6
source     :
    - https://ftp.gnu.org/gnu/libunistring/libunistring-0.9.10.tar.xz : eb8fb2c3e4b6e2d336608377050892b54c3c983b646c561836550863003c05d7
homepage   : http://www.gnu.org/software/libunistring
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Library for manipulating Unicode strings
description: |
    libunistring is a GNU library that provides functions for manipulating Unicdoe strings and for manipulating C strings according to the Unicode standard.
emul32     : yes
patterns   :
    - docs :
        - /usr/share/doc/*
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
