name        : libunistring
version     : 0.9.4
release     : 3
source      :
    - http://ftp.gnu.org/gnu/libunistring/libunistring-0.9.4.tar.xz : 902a391f2351817dcac7f3265cb321edfbbb3f224f180f762da07af133e27fa8
homepage    : http://www.gnu.org/software/libunistring
license     :
    - LGPL-3.0
summary     : Library for manipulating Unicode strings
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    libunistring is a GNU library that provides functions for manipulating Unicdoe strings and for manipulating C strings according to the Unicode standard.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
