name       : libunistring
version    : 0.9.9
release    : 4
source     :
    - http://ftp.gnu.org/gnu/libunistring/libunistring-0.9.9.tar.xz : a4d993ecfce16cf503ff7579f5da64619cee66226fb3b998dafb706190d9a833
homepage   : http://www.gnu.org/software/libunistring
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Library for manipulating Unicode strings
description: |
    libunistring is a GNU library that provides functions for manipulating Unicdoe strings and for manipulating C strings according to the Unicode standard.
emul32     : yes
patterns   :
    - docs :
      - /usr/share/doc/*
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
