name       : libunistring
version    : '1.0'
release    : 7
source     :
    - https://ftp.gnu.org/gnu/libunistring/libunistring-1.0.tar.xz : 5bab55b49f75d77ed26b257997e919b693f29fd4a1bc22e0e6e024c246c72741
homepage   : http://www.gnu.org/software/libunistring
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Library for manipulating Unicode strings
description: |
    libunistring is a GNU library that provides functions for manipulating Unicdoe strings and for manipulating C strings according to the Unicode standard.
emul32     : yes
patterns   :
    - docs :
        - /usr/share/doc/*
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
